[2021-04-25 12:40:39,047] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.create_cluster_dataproc 2021-04-25T10:00:00+00:00 [queued]>
[2021-04-25 12:40:39,083] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.create_cluster_dataproc 2021-04-25T10:00:00+00:00 [queued]>
[2021-04-25 12:40:39,085] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 12:40:39,087] {taskinstance.py:1043} INFO - Starting attempt 3 of 3
[2021-04-25 12:40:39,089] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 12:40:39,106] {taskinstance.py:1063} INFO - Executing <Task(DataprocCreateClusterOperator): create_cluster_dataproc> on 2021-04-25T10:00:00+00:00
[2021-04-25 12:40:39,117] {standard_task_runner.py:52} INFO - Started process 859 to run task
[2021-04-25 12:40:39,122] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'recent_played_ingestion', 'create_cluster_dataproc', '2021-04-25T10:00:00+00:00', '--job-id', '91', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/recent_played_ingestion.py', '--cfg-path', '/tmp/tmpdmckw8ag', '--error-file', '/tmp/tmp1ysjol52']
[2021-04-25 12:40:39,126] {standard_task_runner.py:77} INFO - Job 91: Subtask create_cluster_dataproc
[2021-04-25 12:40:39,191] {logging_mixin.py:104} INFO - Running <TaskInstance: recent_played_ingestion.create_cluster_dataproc 2021-04-25T10:00:00+00:00 [running]> on host 67976f37379c
[2021-04-25 12:40:39,265] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=recent_played_ingestion
AIRFLOW_CTX_TASK_ID=create_cluster_dataproc
AIRFLOW_CTX_EXECUTION_DATE=2021-04-25T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-25T10:00:00+00:00
[2021-04-25 12:40:39,268] {dataproc.py:603} INFO - Creating cluster: ephemeral-recent-played-spark-cluster-20210425
[2021-04-25 12:40:41,446] {dataproc.py:611} INFO - Cluster already exists.
[2021-04-25 12:40:41,796] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=recent_played_ingestion, task_id=create_cluster_dataproc, execution_date=20210425T100000, start_date=20210425T124039, end_date=20210425T124041
[2021-04-25 12:40:41,843] {local_task_job.py:146} INFO - Task exited with return code 1
