[2021-04-23 20:43:58,976] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.create_cluster_dataproc 2021-04-23T18:00:00+00:00 [queued]>
[2021-04-23 20:43:59,033] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.create_cluster_dataproc 2021-04-23T18:00:00+00:00 [queued]>
[2021-04-23 20:43:59,036] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-23 20:43:59,038] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-04-23 20:43:59,042] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-23 20:43:59,065] {taskinstance.py:1063} INFO - Executing <Task(DataprocCreateClusterOperator): create_cluster_dataproc> on 2021-04-23T18:00:00+00:00
[2021-04-23 20:43:59,085] {standard_task_runner.py:52} INFO - Started process 552 to run task
[2021-04-23 20:43:59,103] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'recent_played_ingestion', 'create_cluster_dataproc', '2021-04-23T18:00:00+00:00', '--job-id', '38', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/recent_played_ingestion.py', '--cfg-path', '/tmp/tmp5w93wldt', '--error-file', '/tmp/tmp1inbua5w']
[2021-04-23 20:43:59,114] {standard_task_runner.py:77} INFO - Job 38: Subtask create_cluster_dataproc
[2021-04-23 20:43:59,315] {logging_mixin.py:104} INFO - Running <TaskInstance: recent_played_ingestion.create_cluster_dataproc 2021-04-23T18:00:00+00:00 [running]> on host 760ffd3d790b
[2021-04-23 20:43:59,508] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=recent_played_ingestion
AIRFLOW_CTX_TASK_ID=create_cluster_dataproc
AIRFLOW_CTX_EXECUTION_DATE=2021-04-23T18:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-23T18:00:00+00:00
[2021-04-23 20:43:59,515] {dataproc.py:603} INFO - Creating cluster: ephemeral-recent-played-spark-cluster-20210423
[2021-04-23 20:44:01,870] {dataproc.py:611} INFO - Cluster already exists.
[2021-04-23 20:49:20,515] {dataproc.py:547} INFO - Cluster created.
[2021-04-23 20:49:21,231] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=recent_played_ingestion, task_id=create_cluster_dataproc, execution_date=20210423T180000, start_date=20210423T204358, end_date=20210423T204921
[2021-04-23 20:49:21,991] {local_task_job.py:146} INFO - Task exited with return code 1
