[2021-04-23 20:43:59,247] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.delete_cluster_dataproc 2021-04-23T17:00:00+00:00 [queued]>
[2021-04-23 20:43:59,399] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.delete_cluster_dataproc 2021-04-23T17:00:00+00:00 [queued]>
[2021-04-23 20:43:59,402] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-23 20:43:59,404] {taskinstance.py:1043} INFO - Starting attempt 2 of 2
[2021-04-23 20:43:59,407] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-23 20:43:59,426] {taskinstance.py:1063} INFO - Executing <Task(PatchedDataprocDeleteClusterOperator): delete_cluster_dataproc> on 2021-04-23T17:00:00+00:00
[2021-04-23 20:43:59,437] {standard_task_runner.py:52} INFO - Started process 553 to run task
[2021-04-23 20:43:59,444] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'recent_played_ingestion', 'delete_cluster_dataproc', '2021-04-23T17:00:00+00:00', '--job-id', '39', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/recent_played_ingestion.py', '--cfg-path', '/tmp/tmpt17m7a74', '--error-file', '/tmp/tmpsi4hicr5']
[2021-04-23 20:43:59,450] {standard_task_runner.py:77} INFO - Job 39: Subtask delete_cluster_dataproc
[2021-04-23 20:43:59,567] {logging_mixin.py:104} INFO - Running <TaskInstance: recent_played_ingestion.delete_cluster_dataproc 2021-04-23T17:00:00+00:00 [running]> on host 760ffd3d790b
[2021-04-23 20:43:59,672] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=recent_played_ingestion
AIRFLOW_CTX_TASK_ID=delete_cluster_dataproc
AIRFLOW_CTX_EXECUTION_DATE=2021-04-23T17:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-23T17:00:00+00:00
[2021-04-23 20:43:59,690] {dataproc.py:840} INFO - Deleting cluster: ephemeral-recent-played-spark-cluster-20210423
[2021-04-23 20:44:43,538] {dataproc.py:852} INFO - Cluster deleted.
[2021-04-23 20:44:44,908] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=recent_played_ingestion, task_id=delete_cluster_dataproc, execution_date=20210423T170000, start_date=20210423T204359, end_date=20210423T204444
[2021-04-23 20:44:46,223] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-04-23 20:44:47,560] {local_task_job.py:146} INFO - Task exited with return code 0
